### ISSUE TITLE
CWE-284: Improper Access Control (Team 4) (Critical!)

### ISSUE THREAD

**Issue by MagicianMido32** [ELG7186-s22/project-group-3#13]
As a student, if my instructor limited my access to a certain challenge, I can just create a new instructor user, join this instructor that I created and view any challenge that I like.
It doesn't make sense having multiple instructors in the system with the same privileges' and the same creation mechanism.

**Comment by norantharowat** [comment]
A student can only join one instructor, and we do not support a mechanism for the student to change the instructor after joining that instructor.
So, if a student join an instructor, and that instructor disables the view solutions button, the student will not be able to create a new instructor and join to that instructor, since the student already is under an instructor in the system.

**Comment by MagicianMido32** [comment]
actually he can, just resubmitting the post request of /JoinInstructor in burpsuite, he can change his own instructor.
the control mechanism is handled in the client side but not on the server side 
you should edit the join instructor code and check if this user already have an instructor. 
(you see how overcomplicating your code widens your attack surface ? now you need to check for more possibilities and write more control code)

**Comment by norantharowat** [comment]
Did you try it yourself and succeeded to do so?

Here in the database definition when we assign a student to an instructor, we assign the student id to be unique, so if you try to assign an instructor to the same student with burb, you will get a failed request because the database will refuse to add another student with the same id.

Please inform me if you got a successful request.
 
![image](https://user-images.githubusercontent.com/43759597/183466543-c19a5e6b-f29a-44a8-bb9c-85bd51034586.png)
