### ISSUE TITLE
CWE-203: Observable Discrepancy(team 4)

### ISSUE THREAD

**Issue by atia98** [ELG7186-s22/project-group-3#14]
![WhatsApp Image 2022-08-05 at 1 48 29 AM (1)](https://user-images.githubusercontent.com/57109699/182975877-e66648dc-96ae-4e67-b151-6b08416092e9.jpeg)

a malicious actor can use brute-force techniques (by using large world-list such as rockyou) to either guess or confirm valid usernames in your web Application.

**Comment by norantharowat** [comment]
Brute forcing techniques does not seem to be a threat for this register technique, since you need to provide a captcha on each register attempt, brute forcing techniques can not enter the captcha on each register attempt.

Also, we need to send feedback to the user that the user name they are trying to use is already in use, usernames are not that confidential, it will be a problem if the register sequence requires an email address and you disclose these valid emails.
